### ISSUE TITLE
Price List to be Obtained from uploaded Quotation File

### ISSUE THREAD

**Issue by gladwynlewis83** [badili/erpnext#1]
For the moment, the Price List is not updated from the uploaded Quotation File, or doesn't create a new price list based on the quotation. The problem here is that we cannot use the main Item Price List, because there might be different prices quoted in different quotations for the same Item Number.

**Comment by gladwynlewis83** [comment]
This is essentially the mist critical function at the moment.

**Comment by soloincc** [comment]
**A workaround**
1. Create an empty price list item in ERP
2. Indicate the price list name in the supplier quotation to be uploaded
3. Indicate the prices in the Price List Rate column
4. Upload the supplier quotation
5. It will be uploaded well, with prices appearing well (at this stage the pricing list and rules are empty and all appears well in the suppliers quotation page)
6. Create the pricing RULES using the button _Create pricing rule for quotation_
7. On submitting the quotation, the empty price LIST is automatically populated and linked to the necessary docs
