### ISSUE TITLE
Error while creating Supplier quotation and Purchase order

### ISSUE THREAD

**Issue by gladwynlewis83** [badili/erpnext#10]
![purchaseorder](https://cloud.githubusercontent.com/assets/22613192/19074685/67d612fe-8a52-11e6-9d01-21d49a97781b.jpg)
![supplierqtn](https://cloud.githubusercontent.com/assets/22613192/19074686/67dbd946-8a52-11e6-968f-0c5b147d00f7.jpg)

Please review these odd errors. The fields were in the CSV files, but for some reason not being detected.

**Comment by soloincc** [comment]
Send me the csv files being used.

**Comment by soloincc** [comment]
Fixed!
