### ISSUE TITLE
Proforma Invoice (New Doc Type)

### ISSUE THREAD

**Issue by gladwynlewis83** [badili/erpnext#14]
I know we discussed using the change header field, but the client feels that it is a bit too technical and wants to make it easier. So after Sales Order, the next step would be to create a Proforma Invoice (there is no need of an excel file here, as it would just be PDF). Exact same as the Proforma Invoice is right now with the down payment amount field.

**Comment by soloincc** [comment]
I think this is an extensive modification and maybe we should push it to Phase 2

**Comment by gladwynlewis83** [comment]
Can we duplicate the Payment Request and change the name to proforma, and include the custom fields for the prepayment amounts?

**Comment by soloincc** [comment]
This issue has been split to issue #21
