### ISSUE TITLE
Sales Invoice Fields to make mandatory while importing

### ISSUE THREAD

**Issue by soloincc** [badili/erpnext#17]
Sales Invoice - Warehouse, Sales Order, Delivery Note, Payment Due Date, Quantity, Customer, Item

**Comment by soloincc** [comment]
Are all these new fields in the Sales Invoice?

**Comment by gladwynlewis83** [comment]
These fields are already there. If were doing the custom reports, we don't need to link warehouse.

**Comment by soloincc** [comment]
Done
