### ISSUE TITLE
Minor issues in the Unquoted Items Excel spreadsheets

### ISSUE THREAD

**Issue by soloincc** [badili/erpnext#18]
- If you're attaching unquoted items, you shouldn't need to show $0 value items in the quotation.
- Serial No is yet missing in the Excel Spreadsheet.

**Comment by soloincc** [comment]
I don't understand this issue.

**Comment by gladwynlewis83** [comment]
See the quotation, since we plan to include the $0 items in a separate quotation, shouldn't we be able to separate them? Also the serial number is not appearing in the excel invoice, it goes straight to part numbers.

**Comment by soloincc** [comment]
- We will not be uploading items with 0 in the quotation
- Open a new issue for serial number.
