### ISSUE TITLE
Automatic Date for current date for Supplier and Customer Quotation creation screen.

### ISSUE THREAD

**Issue by gladwynlewis83** [badili/erpnext#3]
This is very important, because we could have the user change the date. My suggestion is to make the date non mandatory, and the system should fill the date automatically (not allow before and after dates)

**Comment by gladwynlewis83** [comment]
I have found this on ERP Next Discuss 

https://discuss.erpnext.com/t/date-custom-script/12291

**Comment by soloincc** [comment]
The date should be automatically be added when uploading csv files

**Comment by gladwynlewis83** [comment]
I've managed to fix this. In all the forms, you just need to remove the mandatory, set it as Read Only, and keep the default value as Today

**Comment by gladwynlewis83** [comment]
This is yet an issue especially for uploaded files. With non uploaded files, it works fine, but in the uploaded file, you can put any date on it. I have even tried making the date field non-mandatory.

**Comment by gladwynlewis83** [comment]
https://frappe.github.io/erpnext/user/manual/en/customize-erpnext/custom-scripts/custom-script-examples/date-validation.html

Either that, or the date is not appearing on the form once it's submitted for some reason.

**Comment by soloincc** [comment]
This was the challenge I foresaw for the documents being uploaded. The link provided is just a date validation when creating the new docs but will not prevent an uploaded document having any date it wants.

The solution to this is either changing the code or using triggers. In the interest of time, we use triggers at the database level. Check out [ERPNext Triggers](https://gist.github.com/soloincc/f652471b102acdc9e88d3d9ac8e616ef). With this, its a temp solution but will work specifically for our case.
