### ISSUE TITLE
Delivery Note: Pricing decimal issue when creating from Sales order (Get items from). Screen shot attached

### ISSUE THREAD

**Issue by gladwynlewis83** [badili/erpnext#8]
![salesorder](https://cloud.githubusercontent.com/assets/22613192/19074622/152851d4-8a52-11e6-864b-90228c8fed1b.jpg)

Please review this odd error because of decimal places, it halts the entire process.

**Comment by soloincc** [comment]
Send me the csv file being used in this

**Comment by gladwynlewis83** [comment]
Try creating a new delivery not from any one of the files, you'll get this error.

**Comment by soloincc** [comment]
Using the import of new business docs, this is as a result of uploading different documents using different decimal point regimes.
