### ISSUE TITLE
Customer Quotation to be linked to Supplier Quotation. 

### ISSUE THREAD

**Issue by gladwynlewis83** [badili/erpnext#9]
This should be allowed in the import list, and in the main fields, so that we can track against which Supplier Quotation, has the Customer Quotation been generated.

**Comment by gladwynlewis83** [comment]
Maybe this could help? 

https://discuss.erpnext.com/t/filtered-dropdown-in-link-field-type/9132

**Comment by soloincc** [comment]
I have moved the supplier quotation from the top level customer quotation to a mandatory field in the Supplier Quotation Item. I am not sure whether this was exactly what was intended

**Comment by gladwynlewis83** [comment]
Partly, but what were looking at is right now in Supplier quotation you can create a purchase order, using the make function. They want the ability to make a customer quotation first, because they want to link the sequence of the processes

**Comment by soloincc** [comment]
Done

**Comment by gladwynlewis83** [comment]
Ok, we've discussed that we will move this to Phase 2 of the project. because this is more focused on the "Make" Function.
